print("Mi primer git.") 
print("Primera linea para guardar git.")
print("Tercera linea para guardar")
print("Cuarta linea para guardar")
print("Quinta linea para guardar")
print("Sexta linea para guardar")
print("Sexta linea para guardar")
print("Septima linea para guardar")
print("Octava linea para guardar")
print("Novema linea para guardar")
